### ISSUE TITLE
Port 6006 Occupied 

### ISSUE THREAD

**Issue by aXb0t** [tyler36/ddev-storybook#10]
For some reason, once I run storybook with the add-on, port 6006 remains occupied despite restarting the container.

If I find and kill the Docker process manually, then port 6006 is available again. Also system restart works. 

Restarting the DDEV container, DDEV poweroff were not able to make port 6006 available again.

Is there a way to restore the `web_extra_exposed_ports` once the container is powered off or restarted?

**Comment by tyler36** [comment]
I did some basic tests.

Its preferable to 

- use `ddev stroybook` to open the project's storybook page (will fail until you start the server)
- use `ddev storybook -s` to start a project's storybook server

I find it easier to open the page, then start the server because I can reuse the same terminal window.
This way, you can run storybook in multiple projects at the same time.

## Test

1. Start project with addon.

```
ddev start
```

1. Attempt to run Storybook locally (not recommended)

```
$ npm run storybook
? Port 6006 is not available. Would you like to run Storybook on port 6008 instead?
```

1. Powerdown DDEV

```
ddev powerdown
```

1. Attempt to run Storybook locally (not recommended)

```
$ npm run storybook
│   Storybook 8.1.9 for vue3-vite started                                                  │
│   392 ms for manager and 248 ms for preview 
```

Works without Docker restart and system restart.

**Comment by aXb0t** [comment]
Thank you for the response..let me try setting this up again on another system at work and see if there is a difference or can possibly discover an error I'm marking

**Comment by aXb0t** [comment]
I think this may have been temporary, possibly related to my workarounds in attempting to get Storybook running. Haven't seen it happen in a couple days so closing.

**Comment by tyler36** [comment]
Thank you for the followup.

Happy to re-open if the issue pops up again.
